/*
 * Copyright 2006-2017 CIRDLES.org.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.cirdles.mcLeanRegression.userInterface;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import org.cirdles.mcLeanRegression.McLeanRegression;

/**
 *
 * @author James F. Bowring
 */
public class AboutBox extends javax.swing.JDialog {

    private final static JDialog INSTANCE = new AboutBox(null, true);

    /**
     * Creates new form AboutBox
     *
     * @param parent
     * @param modal
     */
    private AboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initInstance();
        
    }

    private void initInstance() {
        setSizeAndCenter(400, 400);
        versionLabel.setText(McLeanRegression.VERSION);
        buildDateLabel.setText(McLeanRegression.RELEASE_DATE);
    }

    public static JDialog getInstance() {
        return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        calamariLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        buildDateLabel = new javax.swing.JLabel();
        visitGitHubButton = new javax.swing.JButton();
        warrantyLabel = new javax.swing.JLabel();
        contributorsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(400, 400));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setSize(new java.awt.Dimension(400, 400));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calamariLabel.setBackground(new java.awt.Color(255, 51, 0));
        calamariLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        calamariLabel.setForeground(new java.awt.Color(255, 255, 255));
        calamariLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calamariLabel.setText("Calamari");
        calamariLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calamariLabel.setOpaque(true);
        jLayeredPane1.add(calamariLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 205, -1));

        versionLabel.setBackground(new java.awt.Color(255, 51, 0));
        versionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText("Calamari");
        versionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        versionLabel.setOpaque(true);
        jLayeredPane1.add(versionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 205, -1));

        buildDateLabel.setBackground(new java.awt.Color(255, 51, 0));
        buildDateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        buildDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        buildDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildDateLabel.setText("Calamari");
        buildDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buildDateLabel.setOpaque(true);
        jLayeredPane1.add(buildDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 205, -1));

        visitGitHubButton.setBackground(new java.awt.Color(255, 255, 255));
        visitGitHubButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        visitGitHubButton.setForeground(new java.awt.Color(255, 51, 0));
        visitGitHubButton.setText("Visit us on GitHub");
        visitGitHubButton.setOpaque(true);
        visitGitHubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitGitHubButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(visitGitHubButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 205, 25));

        warrantyLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        warrantyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        warrantyLabel.setText("<html><b>Warranty:</b> Calamari is provided as free open source software on an `as-is' basis.  Use at your own risk.  The developers disclaim all warranties about Calamari.</html>");
        warrantyLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        warrantyLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLayeredPane1.add(warrantyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 360, 70));

        contributorsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        contributorsLabel.setText("<html><b>Contributors:</b><br>&nbsp;Jim Bowring<br>&nbsp;Simon Bodorkos<br>&nbsp;John Zeringue</html>");
        jLayeredPane1.add(contributorsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 200, 150, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visitGitHubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitGitHubButtonActionPerformed
        BrowserControl.showURI("https://github.com/cirdles/mcleanregression");
    }//GEN-LAST:event_visitGitHubButtonActionPerformed

    /**
     *
     * @param preferredWidth
     * @param preferredHeight
     */
    private void setSizeAndCenter(int preferredWidth, int preferredHeight) {
        super.setSize(preferredWidth, preferredHeight);
        super.setPreferredSize(new Dimension(preferredWidth, preferredHeight));

        //Get the screen size
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        //Calculate the frame location
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        //Set the new frame location centered
        setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildDateLabel;
    private javax.swing.JLabel calamariLabel;
    private javax.swing.JLabel contributorsLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JButton visitGitHubButton;
    private javax.swing.JLabel warrantyLabel;
    // End of variables declaration//GEN-END:variables
}
